services:
  loafykitten-cafe:
    container_name: loafykitten-cafe
    image: ${IMAGE_NAME:-ghcr.io/loafykitten/loafykitten-cafe}:${IMAGE_TAG:-main}
    restart: unless-stopped
    networks:
      public-proxy:
        aliases:
          - loafykitten-cafe

networks:
  public-proxy:
    external: true
